### ISSUE TITLE
./downloader.py --name resnet-50 FAILED

### ISSUE THREAD

**Issue by taobiaoli** [opencv/open_model_zoo#107]
./downloader.py --name resnet-50 

###############|| Downloading topologies ||###############

========= Downloading /home/biaolitao/open_model_zoo/model_downloader/classification/resnet/v1/50/caffe/resnet-50.prototxt
Error Connecting: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

###############|| Post processing ||###############

FAILED:
resnet-50

**Comment by alalek** [comment]
@taobiaoli Check your network settings (including proxy settings if any) at first. Are you able to download any other models?

BTW, It would be nice to show on network errors:
- URL of resource (to check link correctness)
- destination path (for manual downloading via browser)
- "curl" command for manual downloading into the destination location (or cache of model downloader).

**Comment by taobiaoli** [comment]
@alalek I've downloaded vgg19, inception V3 model, but resnet50 can't download it.

**Comment by atsyplen** [comment]
@taobiaoli, just use "--num_attempts 10" option. It will attempt each download up to 10 times

**Comment by taobiaoli** [comment]
@alalek I downloaded it manually, url:https://onedrive.live.com/download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117895&authkey=AAFW2-FVoxeVRck
But i using the command that can't download it. I don't know why.

**Comment by Sherry-Zhang** [comment]
I have same problem and I can't download it manually. But I downloaded densenet successfully.

./downloader.py --name 'resnet-*'

###############|| Downloading topologies ||###############

========= Downloading /srv/chenchu/workspace/new_conv_test/open_model_zoo/model_downloader/classification/resnet/v1/50/caffe/resnet-50.prototxt



Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1c04c07978>: Failed to establish a new connection: [Errno 110] Connection timed out',))

========= Downloading /srv/chenchu/workspace/new_conv_test/open_model_zoo/model_downloader/classification/resnet/v1/101/caffe/resnet-101.prototxt
Error Connecting: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

========= Downloading /srv/chenchu/workspace/new_conv_test/open_model_zoo/model_downloader/classification/resnet/v1/152/caffe/resnet-152.prototxt
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117893&authkey=AAFW2-FVoxeVRck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1c04c821d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by atsyplen** [comment]
@Sherry-Zhang, please use --num_attempts option
./downloader.py --name resnet-50 --num_attempts 10

**Comment by Sherry-Zhang** [comment]
@atsyplen Retry is useless. It is failed to establish a new connection. Is there something wrong with onedrive? I can't access onedrive.

**Comment by taobiaoli** [comment]
@Sherry-Zhang 兄弟，我发给你吧

**Comment by Sherry-Zhang** [comment]
@taobiaoli 太感谢了，sherryz@mail.ustc.edu.cn

**Comment by taobiaoli** [comment]
@Sherry-Zhang  试了以下还是百度网盘速度快。
链接: https://pan.baidu.com/s/10qB3fIMXR52z9X3KAhnt-g 提取码: erw2

**Comment by yuhuilix** [comment]
I also have same issue to download resnet50, seem like the URL of resource is not correct:
root@lyh-NUC8i7HVK:/home/lyh/dldt/model_downloader# ./downloader.py --name resnet-50 --num_attempts 10

###############|| Downloading topologies ||###############

========= Downloading /home/lyh/dldt/model_downloader/classification/resnet/v1/50/caffe/resnet-50.prototxt
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...
Error Connecting: HTTPSConnectionPool(host='onedrive.live.com', port=443): Max retries exceeded with url: /download?cid=4006CBB8476FF777&resid=4006CBB8476FF777%2117891&authkey=AAFW2-FVoxeVRck (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Will retry in 10 seconds...

**Comment by IRDonch** [comment]
Looks like OneDrive, where the files for this model are hosted, is blocked in your country. I'm afraid there's nothing we can do about that.
