### ISSUE TITLE
why super resolution has two inputs (single-image-super-resolution-1032 and 1033)

### ISSUE THREAD

**Issue by guoyejun** [opencv/open_model_zoo#1107]
https://github.com/opencv/open_model_zoo/blob/master/models/intel/single-image-super-resolution-1032/description/single-image-super-resolution-1032.md

name: "0" , shape: [1x3x270x480] - An input image in the format [BxCxHxW], 
name: "1" , shape: [1x3x1080x1920] - Bicubic interpolation of the input image in the format [BxCxHxW], 

name '1' can be derived from name '0', why we still need to input '1', and can we provide model file with only one input? thanks.

**Comment by vladimir-dudnik** [comment]
cc @snosov1

**Comment by snosov1** [comment]
See my answer to your previous question as rationale. The "2-input way" is how the model was trained, so that's how we leave the model.

We could "hide" this upscaling inside the model, but, say, the user have means to get the interpolated upscale version optimally or even "for free" from somewhere (e.g. HW optimization, cropping, etc.). If we hide the upscaling - then we spend extra cycles the user doesn't need.
