### ISSUE TITLE
adapter question

### ISSUE THREAD

**Issue by natxopedreira** [opencv/open_model_zoo#1136]
Hello

Sorry to ask something that sure is obvious but i have been searching and found nothing...

Im study some adapters to see how model output data is processed and have some questions

Inside an adapter i see a function called:
`def process(self, raw, identifiers=None, frame_meta=None):`

raw i assume is the output from IECore inference? but what is identifiers and frame_meta?

Is there a sample where i can see and adapter in use?

Thank you!

**Comment by cocokale** [comment]
As the their names indicate, 'identifier' is a variable that identifies an object, such as the image name in the annotation file. 'frame_meta' includes the meta data of an image, e.g. a dictionary with keys such as image size, or scaling parameter, etc.

**Comment by natxopedreira** [comment]
@cocokale  Thank you!

But i must pass some in concrete? Any sample where they are using an adapter?

For example
`identifiers = "name.jpg"`
`frame_meta = {"width": 320, "height":240}`

I mean here they are asking for scale_x, scale_y....
`x_scale, y_scale = meta['scale_x'], meta['scale_y']`

and later they do a loop
`for batch_id, (identifier, meta) in enumerate(zip(identifiers, frame_meta)):`

and if i do a print is a bit nosense
`0 ('n', 'width')`
`1 ('a', 'height')`

**Comment by cocokale** [comment]
identifiers should be a list of image names instead of a single one. Also according to my experience, you don't need to pass them in concrete. Instead, you should prepare something like an annotation file, e.g., for ICDAR13 task, which includes the image names and corresponding labels, separated by '\n'. The accuracy checker tool will automatically do the parameter passing for you.  Please refer to [accuracy checker tool documentation](https://docs.openvinotoolkit.org/latest/_tools_accuracy_checker_README.html) for details.

**Comment by natxopedreira** [comment]
@cocokale thank you

Only wanted to understand what they are passing, as in this function is done a data conversion from raw data to a formated one.

I believed that these parameters were fundamental in the conversion but do not look like
