### ISSUE TITLE
Is resnet-50-tf quantizable?

### ISSUE THREAD

**Issue by qiyuangong** [opencv/open_model_zoo#1230]
In master branch, this model is not quantizable. But, it is in develop branch. :(

Is there any problem (accuracy or performance problem) for resnet-50-tf quantizing? Can I just make it quantizable in my binary installed openvino by changing model.yml?

**Comment by vladimir-dudnik** [comment]
@qiyuangong there should be no issues with quantization of resnet-50 model from TF. We just start adding quantization support through OMZ since OpenVINO 2020.3 release (which OMZ master branch corresponds to) and we started from few models. In upcoming OpenVINO 2020.4 release we are plan to extend number of models which can be quantized through OMZ, although we will not cover all models which potentially could be quantized yet (just need to establish robust validation infrastructure for that). Note, it also should be possible to quantize models through OpenVINO Workbench tool. The benefit we see with quantization through OMZ is that you may quantize models by the list. Please feel free to provide any kind of feedback on this new OMZ functionality. How does it work for you, what can be improved? Thanks in advance.

**Comment by qiyuangong** [comment]
Thanks @vladimir-dudnik 👍 

I have quantized that model into int8. It works well for now. 

I notice that 2020.3 is LTS. Will these `quantized` models available for 2020.3?

**Comment by vladimir-dudnik** [comment]
@qiyuangong we do not provide quantized public models in OpenVINO to reduce download size. There is no choice for Intel models, which use non public datasets and can't be quantized on customer side, so we have to provide such quantized models. For public models situation is different, they can be quantized on customer side, we validate this internally, and for models we know, that can be quantized without significant accuracy drop we provide ability to quantize on customer side.

**Comment by qiyuangong** [comment]
Thanks @vladimir-dudnik for providing detailed explanation. 👍 

Now I understand why only intel models are downloadable.

Have a nice weekend!

Issue closed.
