### ISSUE TITLE
 Suggestion for the current license-plate detection model

### ISSUE THREAD

**Issue by dc-ying** [opencv/open_model_zoo#206]
Hi!
I tried to use vehicle-license-plate-detection-barrier-0106 to detect the license-plate on Raspberry,  but I found the detection model is only suitable for front facing cars. 
While
1. it is the only suitable demo for license-plate, 

2. the text-detection-0002 can not support Raspberry, 

3. the "Barrier" is necessary to detect the back facing cars sometimes ( maybe to detect reverse driving cars ) 

So, I suggest improving the current license detection model or adding new models into demo. 😄

**Comment by snosov1** [comment]
Hey, @dc-ying!

Both front and rear facing plates should be supported (they, actually, look pretty much the same). The plates with out-of-plane and significant in-plane rotations can be missed, that's true.

For text-detection - what do you mean by not supported on Raspberry? The NCS doesn't support it? If yes, then, I believe, the fix is in order. I think (I think) it should be in the upcoming release.

For a new a demo - a great suggestion! Care to train a model and contribute? ;)

**Comment by dc-ying** [comment]
Oh yes, I meant the MYRIAD on NCS for text-detection, sorry for that.
Thanks for your immediate respose !
