### ISSUE TITLE
cannot import name 'IECore'

### ISSUE THREAD

**Issue by YaroslavSchubert** [opencv/open_model_zoo#301]
Hi! I'm running python object detection demo as follows:
```
python object_detection_demo_ssd_async.py -m /home/toutaudio/projects/open_model_zoo/tools/downloader/Retail/object_detection/pedestrian/hypernet-rfcn/0026/dldt/FP16/person-detection-retail-0002.xml -d MYRIAD -i cam
```
but getting error:
```
Traceback (most recent call last):
  File "object_detection_demo_ssd_async.py", line 26, in <module>
    from armv7l.openvino.inference_engine import IENetwork, IECore
ImportError: cannot import name 'IECore'
```
Openvino is installed and setup script `source /opt/intel/openvino/bin/setupvars.sh` is executed .

In another application, I'm using `IENetwork` and `IEPlugin` and it just works.

**Comment by kchechil** [comment]
@YaroslavSchubert what is the version of OpenVINO you're using? Did you take it from https://software.intel.com/en-us/openVINO-toolkit/choose-download ? 
IECore is available since OpenVINO R2, but if you take IE from https://github.com/opencv/dldt - then most likely it's still R1.
Alternatively, you can try to use demos from https://github.com/opencv/open_model_zoo/tree/2019_R1/demos/object_detection_demo_ssd_async
For the question about publication of OpenVINO R2 to Github: cc @moslex @vmatveic 

Hope that it helps.

**Comment by YaroslavSchubert** [comment]
Thanks, @kchechil. Yes, I'm using Openvino R1 but demos are from R2 release.
Fixed by installing Openvino 2019 R2.
