### ISSUE TITLE
what happened to face-person-detection-retail-0002

### ISSUE THREAD

**Issue by YaroslavSchubert** [opencv/open_model_zoo#309]
I found it in 2018R1 model zoo. Curious why it was deleted from 2019R2? 
Existing person detection models doesn't work well with persons that are close to the camera but this model looks like a good fit. 
Any chance to get it to work on 2019R2 release?

**Comment by kchechil** [comment]
@YaroslavSchubert the model has been excluded from the release because there is no dedicated demo that supports it, so the full user story is "broken".
cc @snosov1 to comment on the plans to develop the demo and return the model back to OMZ or provide any workaround by using other models.

**Comment by snosov1** [comment]
Hey, @YaroslavSchubert !

As @kchechil points out, we've removed this model due to the lack of demo and the fact the we've considered the model inferior to the remaining set of models (I'm a bit surprised to hear that it works better than, say, `person-detection-retail-0013` or `pedestrian-detection-adas-0002`). 

That said, if you do find it superior in your use case - do you care enough to contribute the demo that can run it? (Or, maybe, better yet - modify `object_detection_demo_ssd_async` to accept it). If yes, we'll consider bringing it back after we merge the modified demo.

**Comment by YaroslavSchubert** [comment]
Oh, I mislead you :) I didn't try to run `face-person-detection-retail-0002`, just made a hypothesis that it will better suit my needs as it performs person and face detection simultaneously while keeping a similar number of parameters and FLOPS.

**Comment by snosov1** [comment]
Yeah, savings on the model size was the original idea behind it. But it didn't, actually, perform to our expectations, so we've abandoned this thread.
