### ISSUE TITLE
Dynamic batch size example python

### ISSUE THREAD

**Issue by blechatellier** [opencv/open_model_zoo#416]
Is there an example to run dynamic batch sizing in python with the 2019_r2 openvino sdk?

Running into issues because of the shape of the inputs:
```
ValueError: could not broadcast input array from shape (2,3,227,227) into shape (1,3,227,227)
```

**Comment by eaidova** [comment]
You can find a simple example in [inference engine python API overview](https://github.com/opencv/dldt/blob/2019/inference-engine/ie_bridges/python/docs/api_overview.md)
and its usage in the code from [classification_sample](https://github.com/opencv/dldt/tree/2019/inference-engine/ie_bridges/python/sample/classification_sample)

**Comment by blechatellier** [comment]
@eaidova thanks, this example is for normal batching, not dynamic batching though - I've figured that I have to setup `set_batch` on the current request by looking at the c++ code.

**Comment by eaidova** [comment]
@blechatellier, OpenVINO 2019 r2 introduces IECore API for future replacing traditional plugin-based API, so due to both cases works in your package as well, there are some mismatches between samples in docs (the majority of them use IEPlugin instance), But it also will work with IECore with some adoptions (as you noticed `plugin.load(net)` = `ie.load_network(net, device)`, `plugin.set_config(config)` = `ie.set_config(config, device)`)

About the issue with the length of inputs during the inference with dynamic batch size. The length of inputs and outputs always matches to an original batch size which used as the maximal size of the batch for infer request. `set_batch()` does not change the input and output shape, but it has an influence on batch which will be processed inside of InferenceEngine. 
For example, if your network has `net.batch_size = 20` and you set `exec_net.requests[0].set_batch(2)`, so during the inference, only first 2 elements of batch size will be processed, so it promises better performance result if you do not use dynamic batch in the same case.
I hope this sample smooths out the difference in use
```python
from openvino.inference_engine import IECore, IENetwork
import numpy as np

ie = IECore()
net = IENetwork(xml, bin)
net.batch_size = 20
# create executable network with dynamic batch support
exec_net = ie.load_network(net, 'CPU', {"DYN_BATCH_ENABLED": "YES"})
infer_request = exec_net.requests[0]
test_inputs = [np.ones((1, 3, 227, 227)), np.ones((2,3, 227, 227))]

for test_input in test_inputs:
    inputs_count = len(test_input)
    infer_request.set_batch(inputs_count)
    infer_request.inputs[input_blob] = test_input
    infer_request.infer()
    result = infer_request.outputs[output_blob][:inputs_count]
   # do something with result
```
Unfortunattely, change shapes in network connected with memory reallocation, it is expencive operation, so it is the reason why it is not done in this case. The only way out in this situation is to recreate `exec_net` for every input batch with changing network batch size.

**Comment by blechatellier** [comment]
@eaidova makes a lot more sense, thanks for the thorough answer.
