### ISSUE TITLE
An error occurred while cmake compiling

### ISSUE THREAD

**Issue by RachelRen05** [opencv/open_model_zoo#6]
In the **demos** directory, I created a **build** directory for cmake compilation.
command:

`cmake -DCMAKE_BUILD_TYPE=Release ..`

but, an error occurred:

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
intel_omp_lib
    linked by target "cpu_extension" in directory /home/intel/code/open_model_zoo/demos/extension
-- Configuring incomplete, errors occurred!

I found out that this problem was caused by a path error in /open_model_zoo/demos/cmake/feature_defs.cmake:

> find_library(intel_omp_lib iomp5
         PATHS ${InferenceEngine_INCLUDE_DIRS}/../external/mkltiny_lnx/lib
         PATHS ${InferenceEngine_INCLUDE_DIRS}/../temp/mkltiny_lnx_20180511/lib
         )

After modification, cmake can be compiled normally.

**Comment by mweaverh** [comment]
:+1:

**Comment by vmatveic** [comment]
Hi @RachelRen05 ,

How do you use Inference Engine binaries to build the demos? Are you using openVINO R3 binary package and source environment script from there?

**Comment by RachelRen05** [comment]
Hi @vmatveic,
I used the following command to build the demos using Inference Engine:
`cmake -DCMAKE_BUILD_TYPE=Release /home/<hostname>/code/dldt/inference-engine`

I didn't use OpenVINO binary package, I used OpenVINO open source code.
You can refer to: [https://software.intel.com/en-us/forums/computer-vision/topic/798642](https://software.intel.com/en-us/forums/computer-vision/topic/798642)

**Comment by vmatveic** [comment]
Hi @RachelRen05 ,

Let me comment regarding proper way of working with Open Source version of the product:

1. There is **open-model-zoo** repo with a list of demos. These demos are designed to be built separately with the IE environment source before. If you want to build these demos then you need to have OpenVINO package (of appropriate version, currently for R3) installed (can be taken from https://software.intel.com/en-us/openvino-toolkit). Then you need to source an environment from that package (to get InferenceEngine and OpenCV configured for CMake). After that you are able to successfully build demos by creating of own folder and running of “cmake ..” command from here.
1. There is another **dldt** repo which is used to contribute to InferenceEngine core part. If you want to build dldt sources then you can do that like you did (clone dldt repo and build it). Also, it’s implied that the samples from this repo are built together with this dldt project but not separately. If you still want to build these samples separately then you need to copy samples to own location and update its CMake architecture manually + copy extensions here (to have it similar to demos structure within open-model-zoo) and use an environment from an OpenVINO binary package.
1. Also, there is still a possibility to use built dldt binaries like openVINO environment for a separate samples/demos build. You need to set InferenceEngine_DIR to a cmake folder you run “cmake -DGEMM=MKL -DENABLE_MKL_DNN=ON -DCMAKE_BUILD_TYPE=Release ..” command from. But please note, in R3 release this possibility is not completely verified but it’s improved in R4 (also, in R4 you will not need to copy extensions to samples/demos directory, it will be automatically used from binaries).

So, just to repeat, we suggest to use openVINO package (of R version currently) for a separate demos build and use an environment from here. R3 – because current GitHub version of the open source project is adapted to R3 version of openVINO.

Thanks!

**Comment by snosov1** [comment]
Is this still relevant or we can close?

**Comment by snosov1** [comment]
Please, reopen if still relevant
