### ISSUE TITLE
Error reading network: cannot parse future versions: 5

### ISSUE THREAD

**Issue by abc67ok** [opencv/open_model_zoo#71]
when I use person-detection-action-recognition-teacher-0002.xml ,and the newest code of 
"smart_classroom_demo" ,I get the following:
[ ERROR ] Error reading network: cannot parse future versions: 5

Do I need to upgrade something?

**Comment by snosov1** [comment]
Yeah.

Sorry, the models were uploaded a little bit earlier than the upcoming release itself. Once it's out (hopefully, this week) you should be able to run the model. For now, you're better off using the 2018 branch.

**Comment by vmatveic** [comment]
Hi @abc67ok ,

Yes, unfortunately it's expected behavior and it looks the same as https://github.com/opencv/dldt/issues/113 . The idea is that you can't use latest version of open-model-zoo with exact 2018/R5 version of the dldt repo. You need to wait a bit to get the latest version of the dldt repo and 2019/R1 version of the openVINO dostribution toolkit released officially. Only these changes include support of latest version 5 for IR models. So, you can only use 2018/R5 version of the open-model-zoo with 2018/R5 version of the dldt (because dldt is not completely open sourced yet).

Adding f @snosov1 to inform that master version of the open-model-zoo repo can't work with latest available version (2018/R5) of the dldt repo.

**Comment by snosov1** [comment]
@vmatveic Slava, can you make the 2018 branch to be default for now (instead of master) ?

**Comment by alalek** [comment]
@snosov1 omz default branch changed to `2018`
