### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by abhishek11097** [opencv/open_model_zoo#753]
I am trying to run multi_camera_multi_person_tracking.py in python_demos. The command I am trying is 
python3 multi_camera_multi_person_tracking.py \
    -i in-store.mp4 \
    --config config.py \
    --m_reid person-reidentification-retail-0079.prototxt \
    -m person-detection-retail-0013.prototxt \
    -l /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx512.so \
    --output_video output.avi

but i am getting Illegal instruction (core dumped).
Please help

**Comment by eaidova** [comment]
Hi @abhishek11097 
In majority of cases this error says that you use the cpu extension library compiled with instructions which is not supported by your machine (AVX512), please try another lib version or if you build demos in the package, it should also include building cpu extension (it is the most preferable way, because the layer implementation will be compiled with optimisations specific to your machine.)

To avoid further errors, please carefully read README.md provided with demo. As the model, (-m, -m_reid) the demo required OpenVINO intermediate representation (IR) which can be downloaded via model downloader (xml file, not prototxt)

**Comment by abhishek11097** [comment]
Thanks changing the cpu extension solved the problem.
